main: com.massivecraft.massivemarriage.MassiveMarriage
name: MassiveMarriage
version: 2.14.1-SNAPSHOT
website: https://www.massivecraft.com/massivemarriage
description: §eMassiveMarriage allows the players to marry eachother for extra perks.
authors: [RustyTrumbone]
depend: [MassiveCore]

# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
permissions:
  massivemarriage.basecommand: {description: use the MassiveMarriage base command , default: false}
  massivemarriage.propose:     {description: send a proposal to another player, default: false}
  massivemarriage.unpropose:   {description: cancel a proposal sent, default: false}
  massivemarriage.accept:      {description: accept a proposal from another player, default: false}
  massivemarriage.deny:        {description: deny a proposal from another player, default: false}
  massivemarriage.show:        {description: show your current partner, default: false}
  massivemarriage.divorce:     {description: divorce your current partner, default: false}
  massivemarriage.config:      {description: edit the MassiveMarriage config, default: false}
  massivemarriage.version:     {description: display MassiveMarriage version, default: false}

# -------------------------------------------- #
# START NOTATION
# -------------------------------------------- #
massivemarriage.*:
  children:
    massivemarriage.basecommand: true
    massivemarriage.propose: true
    massivemarriage.unpropose: true
    massivemarriage.accept: true
    massivemarriage.deny: true
    massivemarriage.show: true
    massivemarriage.divorce: true
    massivemarriage.config: true
    massivemarriage.version: true

# -------------------------------------------- #
# KITS
# -------------------------------------------- #
  massivemarriage.kit.op:
    default: op
    children:
      massivemarriage.*: true
  massivemarriage.kit.rank3:
    default: false
    children:
      massivemarriage.kit.rank2: true
      massivemarriage.config: true
  massivemarriage.kit.rank2:
    default: false
    children:
      massivemarriage.kit.rank1: true
  massivemarriage.kit.rank1:
    default: false
    children:
      massivemarriage.kit.rank0: true
  massivemarriage.kit.rank0:
    default: false
    children:
      massivemarriage.propose: true
      massivemarriage.unpropose: true
      massivemarriage.accept: true
      massivemarriage.deny: true
      massivemarriage.show: true
      massivemarriage.divorce: true
      massivemarriage.config: true
      massivemarriage.version: true
  massivemarriage.kit.default:
    default: true
    children:
      massivemarriage.kit.rank0: true